# https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/advanced-usage.md
title: The Quiet Readers
email: thequietreaders@outlook.com
description: >- # The ">-" lets you write a long description
  Discover honest romance and fantasy book reviews at The Quiet Readers. 
  An independent blog and dreamy space for book recommendations, movies, series, and gaming.
baseurl: "" 
url: "https://thequietreaders.com" 

lang: en-US
author:
  name: The Quiet Readers
  email: thequietreaders@outlook.com
  twitter: quietreaders # TODO

# Branding for Google Search (Knowledge Graph)
# This uses your largest icon so Google displays it next to your search result
logo: /assets/images/icons/LogoSecondary.png 

# Social Sharing Fallback 
# If a page has no image, Twitter/Facebook will use this one by default.
# TODO: create a generic "The Quiet Readers" banner
image: /assets/images/icons/LogoSecondary.png 

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Navigation links for your header
header_pages:
  - index.html
  - about.md
  - books.md
  - tv.md
  - games.md

# Show one paragraph and a read more button on RSS feed 
# feed:
#   excerpt_only: true